import { PdfBuilder } from './simple-pdf';

function parse(buf: Buffer) {
  const s = buf.toString('latin1');
  const startxref = Number(s.match(/startxref\n(\d+)\n%%EOF\n$/)![1]);
  const xref = s.slice(startxref);
  const [, count] = xref.match(/^xref\n0 (\d+)\n/)!;
  const entries = [...xref.matchAll(/(\d{10}) (\d{5}) ([nf])\r\n/g)].map(
    (m) => ({
      offset: Number(m[1]),
      type: m[3],
    }),
  );
  return { s, startxref, count: Number(count), entries };
}

describe('PdfBuilder', () => {
  it('writes a structurally valid PDF whose xref offsets point at each object', () => {
    const pdf = new PdfBuilder({ title: 'Test (Rx)' })
      .banner(
        'Ayuva Clinic',
        'Dr. Priya Menon · Reg KMC-104233',
        'RX-2026-000001',
      )
      .keyValues([
        ['Patient', 'Amara Okafor'],
        ['Date', '8 Oct 2026'],
      ])
      .heading('Medicines')
      .table(
        [
          { header: 'Medicine', width: 0.5 },
          { header: 'Dose', width: 0.25 },
          { header: 'Duration', width: 0.25, align: 'right' },
        ],
        [['Tab Paracetamol 500 mg', '1-0-1 after food', '5 days']],
      )
      .signature(['Dr. Priya Menon', 'Reg. KMC-104233'])
      .footer('Generated by Ayuva')
      .build();

    const { s, startxref, count, entries } = parse(pdf);
    expect(s.startsWith('%PDF-1.4\n')).toBe(true);
    expect(s.slice(startxref, startxref + 4)).toBe('xref');
    expect(entries).toHaveLength(count);
    expect(entries[0].type).toBe('f');
    entries.slice(1).forEach((e, i) => {
      expect(s.slice(e.offset, e.offset + `${i + 1} 0 obj`.length)).toBe(
        `${i + 1} 0 obj`,
      );
    });
    // Stream lengths must match their content exactly.
    for (const m of s.matchAll(/<< \/Length (\d+) >>\nstream\n/g)) {
      const start = m.index + m[0].length;
      expect(s.slice(start + Number(m[1]), start + Number(m[1]) + 10)).toBe(
        '\nendstream',
      );
    }
  });

  it('escapes PDF string delimiters and maps typographic characters to WinAnsi', () => {
    const s = new PdfBuilder()
      .text('Take (as directed) \\ 2–3 times • 37°C ₹500')
      .build()
      .toString('latin1');
    // Octal escapes are always 3 digits, so "\2263" reads as 0x96 followed by "3".
    expect(s).toContain(
      'Take \\(as directed\\) \\\\ 2\\2263 times \\225 37\\260C Rs.500',
    );
  });

  it('breaks long content onto additional pages', () => {
    const b = new PdfBuilder();
    for (let i = 0; i < 120; i++)
      b.text(`Line ${i} of a long clinical note that keeps going.`);
    const s = b.build().toString('latin1');
    const pages = Number(
      s.match(/\/Type \/Pages \/Kids \[[^\]]*\] \/Count (\d+)/)![1],
    );
    expect(pages).toBeGreaterThan(1);
    expect(s).toContain(`Page ${pages} of ${pages}`);
  });

  it('wraps text to the available width', () => {
    const b = new PdfBuilder();
    const lines = b.wrap('word '.repeat(80).trim(), 200, 10, 'regular');
    expect(lines.length).toBeGreaterThan(1);
    lines.forEach((l) =>
      expect(b.measure(l, 10, 'regular')).toBeLessThanOrEqual(200),
    );
  });
});
