import type { LabParameter } from './schemas/lab-catalog-item.schema';

export interface StarterTest {
  code: string;
  name: string;
  category: string;
  sampleType: string;
  price: number;
  tatHours: number;
  homeCollection: boolean;
  fastingRequired: boolean;
  preparation: string;
  parameters: LabParameter[];
  /** For packages: codes of the tests it bundles. */
  includesCodes?: string[];
}

const p = (
  name: string,
  unit: string | undefined,
  refLow?: number,
  refHigh?: number,
  criticalLow?: number,
  criticalHigh?: number,
): LabParameter => ({ name, unit, refLow, refHigh, criticalLow, criticalHigh });
const t = (name: string, refText: string, unit?: string): LabParameter => ({
  name,
  unit,
  refText,
});

/**
 * Optional starter catalogue a new diagnostic centre can import, then edit.
 * Reference intervals are common adult textbook ranges — each lab must
 * replace them with the ranges validated for its own analysers and methods
 * (the portal says so on import).
 */
export const STARTER_CATALOG: StarterTest[] = [
  {
    code: 'CBC',
    name: 'Complete Blood Count',
    category: 'Haematology',
    sampleType: 'Blood (EDTA)',
    price: 350,
    tatHours: 6,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'No preparation needed.',
    parameters: [
      p('Haemoglobin', 'g/dL', 12, 17, 7, 20),
      p('Total WBC count', 'x10^3/µL', 4, 11, 2, 30),
      p('Platelet count', 'x10^3/µL', 150, 450, 50, 1000),
      p('RBC count', 'x10^6/µL', 4, 6),
      p('Haematocrit (PCV)', '%', 36, 50),
      p('MCV', 'fL', 80, 100),
      p('MCH', 'pg', 27, 32),
      p('MCHC', 'g/dL', 32, 36),
      p('Neutrophils', '%', 40, 75),
      p('Lymphocytes', '%', 20, 45),
      p('Eosinophils', '%', 1, 6),
      p('Monocytes', '%', 2, 10),
    ],
  },
  {
    code: 'FBS',
    name: 'Fasting Blood Sugar',
    category: 'Biochemistry',
    sampleType: 'Blood (Fluoride)',
    price: 100,
    tatHours: 4,
    homeCollection: true,
    fastingRequired: true,
    preparation: 'Fast for 8–10 hours; water is allowed.',
    parameters: [p('Glucose, fasting', 'mg/dL', 70, 99, 50, 400)],
  },
  {
    code: 'HBA1C',
    name: 'HbA1c (Glycated Haemoglobin)',
    category: 'Biochemistry',
    sampleType: 'Blood (EDTA)',
    price: 450,
    tatHours: 12,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'No preparation needed.',
    parameters: [p('HbA1c', '%', 4, 5.6)],
  },
  {
    code: 'LIPID',
    name: 'Lipid Profile',
    category: 'Biochemistry',
    sampleType: 'Blood (Serum)',
    price: 600,
    tatHours: 8,
    homeCollection: true,
    fastingRequired: true,
    preparation: 'Fast for 10–12 hours; water is allowed.',
    parameters: [
      p('Total cholesterol', 'mg/dL', undefined, 200),
      p('Triglycerides', 'mg/dL', undefined, 150),
      p('HDL cholesterol', 'mg/dL', 40),
      p('LDL cholesterol', 'mg/dL', undefined, 100),
      p('VLDL cholesterol', 'mg/dL', 5, 40),
    ],
  },
  {
    code: 'LFT',
    name: 'Liver Function Test',
    category: 'Biochemistry',
    sampleType: 'Blood (Serum)',
    price: 700,
    tatHours: 8,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'No preparation needed.',
    parameters: [
      p('Total bilirubin', 'mg/dL', 0.3, 1.2),
      p('Direct bilirubin', 'mg/dL', 0, 0.3),
      p('SGOT (AST)', 'U/L', 0, 40),
      p('SGPT (ALT)', 'U/L', 0, 41),
      p('Alkaline phosphatase', 'U/L', 44, 147),
      p('Total protein', 'g/dL', 6, 8.3),
      p('Albumin', 'g/dL', 3.5, 5),
    ],
  },
  {
    code: 'KFT',
    name: 'Kidney Function Test',
    category: 'Biochemistry',
    sampleType: 'Blood (Serum)',
    price: 650,
    tatHours: 8,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'No preparation needed.',
    parameters: [
      p('Urea', 'mg/dL', 15, 40),
      p('Creatinine', 'mg/dL', 0.6, 1.3, undefined, 5),
      p('Uric acid', 'mg/dL', 3.5, 7.2),
      p('Sodium', 'mmol/L', 135, 145, 120, 160),
      p('Potassium', 'mmol/L', 3.5, 5.1, 2.5, 6.5),
      p('Chloride', 'mmol/L', 98, 107),
    ],
  },
  {
    code: 'TFT',
    name: 'Thyroid Profile (T3, T4, TSH)',
    category: 'Immunoassay',
    sampleType: 'Blood (Serum)',
    price: 550,
    tatHours: 12,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'No preparation needed.',
    parameters: [
      p('T3, total', 'ng/dL', 80, 200),
      p('T4, total', 'µg/dL', 5.1, 14.1),
      p('TSH', 'µIU/mL', 0.27, 4.2),
    ],
  },
  {
    code: 'VITD',
    name: 'Vitamin D (25-OH)',
    category: 'Immunoassay',
    sampleType: 'Blood (Serum)',
    price: 1200,
    tatHours: 24,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'No preparation needed.',
    parameters: [p('25-OH Vitamin D', 'ng/mL', 30, 100)],
  },
  {
    code: 'VITB12',
    name: 'Vitamin B12',
    category: 'Immunoassay',
    sampleType: 'Blood (Serum)',
    price: 900,
    tatHours: 24,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'No preparation needed.',
    parameters: [p('Vitamin B12', 'pg/mL', 197, 771)],
  },
  {
    code: 'URINE-RE',
    name: 'Urine Routine & Microscopy',
    category: 'Clinical Pathology',
    sampleType: 'Urine (mid-stream)',
    price: 150,
    tatHours: 4,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'Early-morning mid-stream sample preferred.',
    parameters: [
      t('Colour', 'Pale yellow'),
      t('Appearance', 'Clear'),
      p('pH', undefined, 4.6, 8),
      p('Specific gravity', undefined, 1.005, 1.03),
      t('Protein', 'Negative'),
      t('Glucose', 'Negative'),
      p('Pus cells', '/hpf', 0, 5),
      p('Red blood cells', '/hpf', 0, 2),
    ],
  },
  {
    code: 'CRP',
    name: 'C-Reactive Protein',
    category: 'Immunoassay',
    sampleType: 'Blood (Serum)',
    price: 500,
    tatHours: 6,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'No preparation needed.',
    parameters: [p('CRP', 'mg/L', 0, 5)],
  },
  {
    code: 'ESR',
    name: 'Erythrocyte Sedimentation Rate',
    category: 'Haematology',
    sampleType: 'Blood (Citrate)',
    price: 100,
    tatHours: 4,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'No preparation needed.',
    parameters: [p('ESR', 'mm/hr', 0, 20)],
  },
  {
    code: 'NS1',
    name: 'Dengue NS1 Antigen',
    category: 'Serology',
    sampleType: 'Blood (Serum)',
    price: 600,
    tatHours: 6,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'No preparation needed.',
    parameters: [t('Dengue NS1 antigen', 'Negative')],
  },
  {
    code: 'XRAY-CHEST',
    name: 'X-Ray Chest PA View',
    category: 'Radiology',
    sampleType: 'Imaging',
    price: 400,
    tatHours: 2,
    homeCollection: false,
    fastingRequired: false,
    preparation: 'Remove metal objects and jewellery.',
    parameters: [{ name: 'Findings' }, { name: 'Impression' }],
  },
  {
    code: 'USG-ABD',
    name: 'Ultrasound Whole Abdomen',
    category: 'Radiology',
    sampleType: 'Imaging',
    price: 1200,
    tatHours: 4,
    homeCollection: false,
    fastingRequired: true,
    preparation:
      'Fast for 6 hours; drink water an hour before so the bladder is full.',
    parameters: [{ name: 'Findings' }, { name: 'Impression' }],
  },
  {
    code: 'ECG',
    name: 'Electrocardiogram (12-lead)',
    category: 'Cardiology',
    sampleType: 'None',
    price: 300,
    tatHours: 1,
    homeCollection: true,
    fastingRequired: false,
    preparation: 'No preparation needed.',
    parameters: [
      { name: 'Rhythm' },
      p('Heart rate', 'bpm', 60, 100, 40, 150),
      { name: 'Impression' },
    ],
  },
  {
    code: 'PKG-BASIC',
    name: 'Basic Health Check-up',
    category: 'Package',
    sampleType: 'Blood + Urine',
    price: 1999,
    tatHours: 24,
    homeCollection: true,
    fastingRequired: true,
    preparation: 'Fast for 10–12 hours; water is allowed.',
    parameters: [],
    includesCodes: ['CBC', 'FBS', 'LIPID', 'LFT', 'KFT', 'TFT', 'URINE-RE'],
  },
];
